- name: Accepting Oracle JDK license.
  debconf: name=oracle-java8-installer question='shared/accepted-oracle-license-v1-1' value=true vtype='select'
  
- name: install dependencies
  apt: name={{item}}  state=present  update_cache=yes
  with_items:  
    - apt-transport-https
    - python-pip
    - ca-certificates
    - sudo
    - wget
    - curl
    - python-passlib
    - oracle-java8-installer
    - logstash
    - kibana
    - nginx
    - elasticsearch
